POC/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts.views import (index, user_logout, account_view, health_check,
                            transactions, append_bet, validate_username)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^_ah/health', health_check, name='health_check'),
    url(r'^_ah/vm_health', health_check, name='health_check1'),
    url(r'^$', append_bet, name='index'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^epl/$', append_bet, name='epl'),
    url(r'^account/$', account_view, name='account'),
    url(r'^transactions/$', transactions, name='transactions'),
    url(r'tabs/', include('tabs.urls')),
]

accounts/urls.py
from django.conf.urls import url
from accounts import views

# SET THE NAMESPACE!
app_name = 'accounts'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^register/$', views.signup, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^ajax/validate_username/$',
        views.validate_username, name='validate_username'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^forgot_password/$', views.forgot_password, name='forgot_password'),
    url(r'^reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.set_password, name='set_password'),
]

tabs/urls.py
from django.conf.urls import url
from tabs import views

# SET THE NAMESPACE!
app_name = 'tabs'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^just-the-tip/$', views.just_the_tip, name='just-the-tip'),
    url(r'^wishlist/$', views.wishlist, name='wishlist'),
    url(r'^how-it-works/$', views.how_it_works, name='how-it-works'),
    url(r'^prizes/$', views.prizes, name='prizes'),
    url(r'^pools/$', views.pools_view, name='pools'),
    url(r'^pools/pool/(?P<pool_id>\d+$)', views.pool_view, name='pool')
]

tabs/models.py
from django.db import models

# Create your models here.


class WishList(models.Model):
    """
    Place to store wishlist items in the database.
    """
    header = models.CharField(max_length=20)
    text = models.CharField(max_length=1000)
    date_added = models.DateTimeField(auto_now_add=True)
    viewed = models.BooleanField(default=False)

    def __str__(self):
        return self.header + " Note this has a date_added field"

tabs/forms.py
from django import forms
from tabs.models import WishList


class WishListForm(forms.ModelForm):
    text = forms.CharField(widget=forms.TextInput())

    class Meta:
        model = WishList
        fields = ('header', 'text')

tabs/views.py
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.db.models.query import QuerySet
from django.http import request

import json

from tabs.forms import WishListForm
from accounts.models import GamePool, Profile, Pools


@login_required
def pools_view(request):
    """
    Show all pools availible to join.
    Join availible pools, create pools if they don't exist.
    :param request: http request
    :return: render view in html template (pools.html)
    """
    if request.is_ajax():
        return render_pools(request)

    pool_list = create_pool_list(request)

    return render(request, 'tabs/pools.html', {'pools': pool_list})


def create_pool_list(request: request) -> list:
    """Return a list of pools with the members ranking and movements"""
    #  Get a list of all pools

    try:
        user = Profile.objects.get(user=request.user.id)
    except (ObjectDoesNotExist, NameError):
        return []

    pools = []
    pools = user.pools.all()
    if not pools:
        return pools

    pool_list = []
    for pool in pools:
        rank = list(Pools.objects.filter(pool_name=pool, member=user).order_by(
            '-date').values_list('rank', flat=True)[:2])
        standing = 0
        try:
            standing = rank[0]
            movement = rank[1] - rank[0]
        except IndexError:
            movement = 0
        pool_dict = {'pool_standing': standing,
                     'members_in_pool': Pools.objects.filter(
                         pool_name=pool).order_by().values_list('member',
                                                                flat=True).distinct().count(),
                     'pool_name': pool,
                     'pool_movement': movement,
                     'pk': pool.pk}
        pool_list.append(pool_dict)

    return pool_list


def render_pools(request):
    if request.is_ajax():
        pass


@login_required
def pool_view(request, pool_id=None):
    """
    Render the current pool rankings and the graph showing movement.
    :param request:
    :param pool_id: id of the pool to render.
    :return:
    """
    pool_name = GamePool.objects.get(pk=pool_id)
    members = Pools.objects.filter(pool_name=pool_name).order_by().values_list('member', flat=True).distinct()
    pool_ranking = Pools.objects.filter(pool_name=pool_name).order_by('-date', 'accrued_monies')
    # take the top x members from the pool and reverse the order.
    latest_rankings = list(pool_ranking)[:len(members)][::-1]

    rankings_list = {}
    for member in members:
        rankings_list[str(Profile.objects.get(pk=member))] = list(Pools.objects.values('rank', 'date').filter(member=member, pool_name=pool_name).order_by('date'))

    parse_dates(rankings_list)
    dates = Pools.objects.filter(pool_name=pool_name).order_by('date').values_list('date', flat=True).distinct()
    try:
        min_dates = str(min(dates))
        max_dates = str(min(dates))
    except ValueError:
        return render(request, 'tabs/pool.html', {'no_rankings': True})

    return render(request, 'tabs/pool.html', {"pool_ranking": latest_rankings,
                                              "rankings": rankings_list,
                                              "dates": {"min": min_dates,
                                                        "max": max_dates}}
                  )


def parse_dates(rankings_object):
    """
    Format all datetime.date objects in the rankings object
    Updates the dictionary in place.
    :param rankings_object: {'tom':
    [{'rank': 2, 'date': datetime.date(2018, 2, 17)}, {'rank': 2,
    'date': datetime.date(2018, 4, 9)}, {'rank': 1, 'date': datetime.date(...
    :return: dates in the format var format = d3.time.format("%Y-%m-%d");
    """
    for member, result in rankings_object.items():
        for row in result:
            row['date'] = str(row['date'])


def just_the_tip(request):
    return render(request, 'tabs/just-the-tip.html')


def how_it_works(request):
    return render(request, 'tabs/how-it-works.html')


def prizes(request):
    return render(request, 'tabs/prizes.html')


def pools(request):
    return render(request, 'tabs/pools.html')


def registration_modal(request):
    return render(request, 'tabs/registration-modal.html')


def wishlist(request):
    """
    Submit wishlist items to the database to be read by us.
    """
    submitted = False

    if request.method == 'POST':
        wish_form = WishListForm(data=request.POST)

        if wish_form.is_valid():
            wish_form.save()
            submitted = True

    else:
        wish_form = WishListForm()

    return render(request, 'tabs/wishlist.html', {
        'wish_form': wish_form, 'submitted': submitted
    })

templates/tabs/just-the-tip.html
{% extends 'accounts/base.html' %}

{% block left_sidebar %}
    {% include "tabs/left-sidebar.html" %}
{% endblock %}

{% block body_block %}
<div class="main-content">
    <h2>Just the tip</h2>
    <hr class="my-3">
    <p>Each week, one of PuntDoctor’s 3 founders will give you some valuable (this is highly debatable) insights into what they think are the week’s best bets. These tips can be from a variety of sports. We will also bring you guest Tipsters who will share their knowledge to help you make your picks.</p>
    <div class="row p-1">
        <div class="col tipper">
            <div>
                <div class="tipper-image"></div>
                <p class="tipper-name">RugbyMadRobdog</p>
                The man behind the PuntDoctor concept has always been a sports addict but rugby is where his heart lies. Back in his youthful days, he made a few guest appearances on ENEWS as a rugby analyst (he predicted both of his games incorrectly on live television as the pressure of the cameras got to him). Loves taking a punt with his business partner ‘Tipster Tom’ (the self-proclaimed king of Football).
                <div class="betting-tip tip-rob">
                    <p><span>&#8220</span>Never support a sports team (this coming from a massive Lions fan).
                    Loves handicap and over/under points betting  on rugby (the bookies often get it seriously wrong).<span>&#8221</span></p>
                </div>
            </div>
        </div>
        <div class="col tipper">
            <div>
                <div class="tipper-image"></div>
                <p class="tipper-name">Tipster Tom</p>
                Doesn’t mind a few beers watching the Premier League. Football Junkie who in his own words has yet to win a bet on Football (be very careful when following his picks). He did predict at the start of last seasons Premier League that Chelsea would walk it and he wasn’t wrong (but then again, half the world predicted the same).
                <div class="betting-tip tip-tom">
                    <p><span>&#8220</span>Always bet more than you can afford.
                    The English Premier League is far too easy to predict.<span>&#8221</span></p>
                </div>
            </div>
        </div>
        <div class="col tipper">
            <div>
                <div class="tipper-image"></div>
                <p class="tipper-name">Dangerous Dan</p>
                The brains behind the software of PuntDoctor, he would be a rich man if he was as successful as sports betting as he is developing software. Never follows Tipster Tom’s betting advice (to his own detriment).
                <div class="betting-tip tip-dan">
                    <p><span>&#8220</span>Take easy money early<span>&#8221</span></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block right_sidebar %}
{% endblock %}

templates/tabs/left-sidebar.html
<div class="left-sidebar">
    <ul class="sidebar-nav">
        <li><a href="{% url 'epl' %}"><i class="fa fa-home" aria-hidden="true"></i>Home</a></li>
        <li><a href="{% url 'tabs:just-the-tip' %}"><i class="fa fa-lightbulb-o" aria-hidden="true"></i>Just the Tip</a></li>
        <li><a href="{% url 'tabs:pools' %}"><i class="fa fa-users" aria-hidden="true"></i>Pools</a></li>
        <li><a href="{% url 'transactions' %}"><i class="fa fa-list-alt" aria-hidden="true"></i>Transactions</a></li>
        <li><a href="{% url 'tabs:how-it-works' %}"><i class="fa fa-info-circle" aria-hidden="true"></i>How it works</a></li>
        <li><a href="{% url 'tabs:prizes' %}"><i class="fa fa-trophy" aria-hidden="true"></i>Prizes</a></li>
        <li><a href="{% url 'account' %}"><i class="fa fa-user-circle" aria-hidden="true"></i>Account</a></li>
        <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>Log Out</a></li>
    </ul>
    <div class="pool-standings">
        {% if pools_sidebar %}
        {% for pool in pools_sidebar %}
        <a href="#">
            <div class="pool-item row no-gutters">
                <div class="col pool-name-sidebar">{{ pool.pool_name }}</div>
                {% if pool.pool_movement > 0 %}
                <div class="col text-right standing">{{ pool.pool_standing }}/{{ pool.members_in_pool }}<span class="change up"><i class="fa fa-caret-up" aria-hidden="true"></i>{{ pool.pool_movement }}</span></div>
                {% elif pool.pool_movement < 0 %}
                <div class="col text-right standing">{{ pool.pool_standing }}/{{ pool.members_in_pool }}<span class="change down"><i class="fa fa-caret-down" aria-hidden="true"></i>{{ pool.pool_movement }}</span></div>
                {% else %}
                <div class="col text-right standing">{{ pool.pool_standing }}/{{ pool.members_in_pool }}</div>
                {% endif %}
            </div>
        </a>
        {% endfor %}
        {% endif %}
    </div>
</div>

templates/tabs/pool.html
{% extends 'accounts/base.html' %}
{% block javascript %}

<script>
    function myFunction() {
        var input, filter, ul, li, a, i, form;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        ul = document.getElementsByClassName("myUL2");
        console.log(ul);
        for (i = 0; i < ul.length; i++) {
            a = ul[i].getElementsByTagName("a")[0];
            console.log(ul[i]);
            if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
                console.log(a.innerHTML);
                ul[i].style.display = "";
            } else {
                ul[i].style.display = "none";
            }
        }
    }

    function renderPool(poolName){
        var csrf = $("#token input[name='csrfmiddlewaretoken']").val();
        console.log(csrf);
        $.ajax({
            url: "{% url 'tabs:pools' %}",
            type: "POST",
            data:{
                'csrfmiddlewaretoken': csrf,
                'pool_name': poolName
            },
            success: function(response) {
                console.log(response);
                // TODO: Render pool info.
            },
            error: function(err) {
                console.log("Error with rendering of the pool.");
                console.log(err);
            }
        });
    };

</script>
{% endblock %}
{% block left_sidebar %}
{% include "tabs/left-sidebar.html" %}
{% endblock %}

{% block body_block %}
<div class="main-content">
    <h2>{{ pool_ranking.0.pool_name }}</h2>
    <h3>{{ pool_ranking.0.date|date:"d F Y" }}</h3>
    <hr class="my-3">
    {% if no_rankings %}
    {#        TODO: Styling @paddy #}
    <div>No Rankings, check back in a few days</div>
    {% else %}
    <div class="pool-detail" id="{{ pool_ranking.pool_name }}">
        <table class="pool-rankings">
            {% for pr in pool_ranking %}
            <tr>
                <td class="rank">
                    <div>{{pr.rank}}</div>
                </td>
                <td class="tag">
                    <div></div>
                </td>
                <td class="username">
                    {{ pr.member }}
                </td>
                <td class="monies">
                    R{{ pr.accrued_monies }}
                </td>
                <td class="change">
                    <span class="position-change up">{{ pool_ranking.pool_movement }}<i class="fa fa-caret-up"
                                                                                        aria-hidden="true"></i></span>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <hr class="my-3">
    <div style="font: 10px sans-serif;margin: 0 auto;width: 100%;" class="chart"></div>
    {% endif %}
</div>

<script>
    var data = {{ rankings|safe }};
    var dates = {{ dates|safe }};

    // TODO Paddy: Move all javascript into a .js file. Leave all templated vars as they are
    // https://gist.github.com/trtg/3922684
    d3.selection.prototype.moveToFront = function() {
        return this.each(function(){
            this.parentNode.appendChild(this);
        });
    };

    var margin = {top: 20, right: 50, bottom: 30, left: 50},
        width = 960 - margin.left - margin.right,
        height = 300 - margin.top - margin.bottom;

    var x = d3.time.scale()
        .range([0, width]);

    var y = d3.scale.linear()
        .range([height, 0]);

    var format = d3.time.format("%Y-%m-%d");

    var xAxis = d3.svg.axis()
        .scale(x)
        .orient('bottom')
        .tickFormat(function(d) { return d.getFullYear() + '/' + (d.getMonth() + 1) +'/' + d.getDate(); });

    var yAxis = d3.svg.axis()
        .scale(y)
        .orient('left');

    var yAxisRight = d3.svg.axis()
        .scale(y)
        .orient('right');


    var line = d3.svg.line()
        .x(function(d) { return x(format.parse(d.date)); })
        .y(function(d) { return y(d.rank); })
        .interpolate('monotone');


    var colors = d3.scale.category20();

    var svg = d3.select('.chart').append('svg')
        .attr('width', width + margin.left + margin.right)
        .attr('height', height + margin.top + margin.bottom)
        .append('g')
        .attr('transform', 'translate(' + margin.left + ',' + margin.top + ')');

    var minDate = format.parse(dates.min);
    var maxDate = format.parse(dates.max);

    var teamNames = Object.keys(data);
    var teamData = teamNames.map(function(t, i) {
        return { name: t, values: data[t], index: i };
    });
    x.domain([minDate, maxDate]);
    y.domain([teamNames.length + 0.5, 1]);

    svg.append('g')
        .attr('class', 'x axis')
        .attr('transform', 'translate(0,' + height + ')')
        .call(xAxis);

    svg.append('g')
        .attr('class', 'y axis')
        .call(yAxis);

    d3.select('svg').append('g')
        .attr('class', 'y axis')
        .attr('transform', 'translate(' + (width + margin.left) + ',' + margin.top + ')')
        .call(yAxisRight);

    var ranks = svg.append('g').selectAll('.line')
        .data(teamData)
        .enter()
        .append('path')
        .attr('class', 'line')
        .attr('d', function(d) { return line(d.values); })
        .attr('data-team', function(d) { return d.name; })
        .attr('data-team-index', function(d, i) { return i; })
        .style({
            stroke: function(d, i) { return colors(i); }
        })
        .on('click', function(e) {
            removeSelection();
            var selector = 'div[data-team-index=\'' + e.index + '\']';
            d3.select(this).classed('selected', true).moveToFront();
            d3.select(selector).classed('selected', true);
        });

    var teams = teamData.map(function(d, i) {
        return {
            name: d.name.toLowerCase(),
            display: d.name,
            index: i,
            color: colors(i)
        };
    });
    teams.sort(function(a, b) {
        if ( a.name < b.name ) { return -1 };
        if ( a.name > b.name ) { return 1 };
        return 0;
    });
    var legend = d3.select('.chart').append('div')
        .attr('class', 'team-name-container');

    legend.selectAll('.team-name')
        .data(teams)
        .enter()
        .append('div')
        .attr('class', 'team-name')
        .attr('data-team-index', function(d) { return d.index; })
        .style({
            color: function(d) { return d.color; },
            'border-color': function(d) { return d.color; }
        })
        .text(function(d) { return d.display; })
        .on('click', function(e) {
            removeSelection();
            var selector = 'path[data-team-index=\'' + e.index + '\']';
            d3.select(this).classed('selected', true);
            d3.select(selector).classed('selected', true).moveToFront();
        });

    function removeSelection() {
        d3.select('.team-name.selected').classed('selected', false);
        d3.select('.line.selected').classed('selected', false);
    }
</script>
{% endblock %}

templates/tabs/pools.html
{% extends 'accounts/base.html' %}
{% block javascript %}

<script>

    function myFunction() {
        var input, filter, ul, li, a, i, form;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        ul = document.getElementsByClassName("myUL2");
        console.log(ul);
        for (i = 0; i < ul.length; i++) {
            a = ul[i].getElementsByTagName("a")[0];
            console.log(ul[i]);
            if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
                console.log(a.innerHTML);
                ul[i].style.display = "";
            } else {
                ul[i].style.display = "none";
            }
        }
    }

    function renderPool(poolName){
        var csrf = $("#token input[name='csrfmiddlewaretoken']").val();
        console.log(csrf);
        $.ajax({
            url: "{% url 'tabs:pools' %}",
            type: "POST",
            data: {
                'csrfmiddlewaretoken': csrf,
                'pool_name': poolName
            },
            success: function (response) {
                console.log(response);
                // TODO: Render pool info.
            },
            error: function (err) {
                console.log("Error with rendering of the pool.");
                console.log(err);
            }
        });
    };

    $(".pool").click(function () {
        window.location.href += 'pool/' + $(this).attr('id');
    });

</script>
{% endblock %}
{% block left_sidebar %}
{% include "tabs/left-sidebar.html" %}
{% endblock %}

{% block body_block %}
<div>
    <div class="pools container-fluid p-0">
        <!--For loop this whole pool-container-->
        <div class="row">
            {% if pools %}
            {% for pool in pools %}
            <div class="col-12 mb-3">
                <div class="pool" id="{{ pool.pk }}">
                    <table class="pool-summary">
                        <tr>
                            <td class="pool-summary-name">
                                <h4 class="mb-0">{{ pool.pool_name }}</h4>
                            </td>
                            <td class="pool-summary-standing text-right">
                                <span class="field-name">position</span>{{ pool.pool_standing }}/{{ pool.members_in_pool }}
                            </td>
                            <td class="pool-summary-change text-right">
                                {% if pool.pool_movement > 0 %}
                                    <span class="field-name">change</span>
                                    <span class="position-change up">{{ pool.pool_movement }}<i class="fa fa-caret-up" aria-hidden="true"></i></span>
                                {% elif pool.pool_movement < 0 %}
                                    <span class="field-name">change</span>
                                    <span class="position-change down">{{ pool.pool_movement }}<i class="fa fa-caret-down" aria-hidden="true"></i></span>
                                {% else %}
                                    <span class="field-name">-</span>
                                    <span class="position-change">{{ pool.pool_movement }}<i class="fa fa-caret-left" aria-hidden="true"></i></span>
                                {% endif %}
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/tabs/prizes.html
{% extends 'accounts/base.html' %}

{% block left_sidebar %}
    {% include "tabs/left-sidebar.html" %}
{% endblock %}

{% block body_block %}
    <div class="main-content">
        <h2>Prizes and Disclaimers</h2>
        <hr class="my-3">

        <h4 class="mt-4">Cash Prizes</h4>
        <p>We don’t mess around at PuntDoctor and we reward our winners handsomely. We all know that whenever money is involved, the stakes are higher, people take it more seriously and the adrenaline pumps. Ever watch a game of lawn bowls think ‘man that is boring’. However, take a punt on it and suddenly it seems you are watching the Rugby World Cup Final.</p>

        <h4 class="mt-4">Grand Prizes</h4>

        <p>The following prizes apply to the first 5 players in the World Pool (yes your eyes are not deceiving you).</p>

        <ul class="prize-list">
            <li><p><span>1st Place</span> - R50 000</p></li>
            <li><p><span>2nd Place</span> – R20 000</p></li>
            <li><p><span>3rd Place</span> -  R10 000</p></li>
            <li><p><span>4th Place</span> – R6 000</p></li>
            <li><p><span>5th Place</span> – R4 000</p></li>
        </ul>

        <p>Not a bad prize pool for a FREE competition!</p>


    </div>
{% endblock %}

templates/tabs/registration-modal.html
{% extends "accounts/base.html" %}
{% load staticfiles %}
{% block javascript %}
<script>
    $("#id_username").change(function () {
        var username = $(this).val();
        $.ajax({
            url: "{% url 'accounts:validate_username' %}",
            data: {
                'username': username
            },
            dataType: 'json',
            success: function (data) {
                if (data.is_taken) {
                    alert("A user with this username already exists.");
                }
            }
        });
    });
</script>
{% endblock %}
{% block body_block %}

<!-- The Modal -->
<div id="myModal" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
        <span class="close">&times;</span>
        <p>Some text in the Modal..</p>
    </div>

    <div class="registration-page">
        {% if registered %}
        <h1>Thank you for registering!</h1>
        {% else %}
        <section class="container registration-form">
            <div class="row">
                <div class="col-6">
                    <h2>Registration</h2>
                    <hr class="my-3">

                    {% if registered %}
                    <h1>Thank you for registering!</h1>
                    {% else %}
                    <form enctype="multipart/form-data" method="POST">
                        {% csrf_token %}
                        {{ user_form.as_p }}
                        {{ profile_form.as_p }}
                        <input class="btn btn-link" type="submit" name="" value="Register">
                    </form>
                    {% endif %}
                </div>

                <div class="col-6 terms-and-conditions">
                    <h2>Terms & Conditions</h2>
                    <hr class="my-3">
                    <p>
                        By clicking on "Register" you agree to The Company's Terms and Conditions
                    </p>
                    <p>
                        Here are the T's & C's
                    </p>
                    <p>
                        Here are the T's & C's
                    </p>
                    <p>
                        Here are the T's & C's
                    </p>


                </div>
            </div>
            <!--<div class="row">-->
            <!--<div class="col-12 text-center mt-4">-->
            <!--<button type="submit" class="btn btn-primary">Register</button>-->
            <!--</div>-->
            <!--</div>-->
        </section>
        {% endif %}
        <div class="bottom-spacer"></div>
    </div>
</div>

{% endblock %}

templates/tabs/slip.html
{% extends "accounts/base.html" %}
{% block body_block %}

<div class="full-background">
    {% if user.is_authenticated %}
        <!--<h2>Welcome {{ user.username }}!</h2>-->
    {% else %}

        <div class="container">
            {% load staticfiles %}
            <div class="jumbotron landing-login">
                <div class="container">
                    <div class="row">
                        <div class="col-8">
                            <h1 class="display-3">Welcome to PuntDoctor</h1>
                            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
                        </div>
                        <div class="col-4 text-right">
                            <img src="{% static "doctor.png" %}" alt="PuntDoctor Logo" width="200">
                        </div>
                    </div>
                    <hr class="my-4">
                    <div class="row">
                        <div class="col">



                            <!--<a href="#" class="navbar-form navbar-right">-->
                                <!--<div>-->
                                    <!--<form method="post" action="{% url 'accounts:user_login' %}">-->
                                        <!--{% csrf_token %}-->
                                        <!--<input class="login-form" type="text" name="username" class="form-control" placeholder="Username">-->
                                        <!--<input class="login-form" type="password" name="password" class="form-control" placeholder="Password">-->
                                        <!--<input class="navbar-login" type="submit" name="" value="Login">-->
                                    <!--</form>-->
                                <!--</div>-->
                            <!--</a>-->
                            <!--<li><a class="nav-link" href="{% url 'accounts:register' %}">Register</a></li>-->

                            <form class="form-inline method="post" action="{% url 'accounts:user_login' %}">
                                {% csrf_token %}
                                <label class="sr-only" for="inlineFormInput">Name</label>
                                <input type="text" name="username" class="form-control mb-2 mr-sm-2 mb-sm-0" id="inlineFormInput" placeholder="Username">
                                <label class="sr-only" for="inlineFormInputGroup">Username</label>
                                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                    <input type="text" name="password" class="form-control" id="inlineFormInputGroup" placeholder="Password">
                                </div>
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a class="register-button" href="{% url 'accounts:register' %}">Register</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endif %}
</div>

{% endblock %}

templates/tabs/wishlist.html
{% extends 'accounts/base.html' %}

{% block left_sidebar %}
    {% include "tabs/left-sidebar.html" %}
{% endblock %}

{% block body_block %}
<div class="main-content">
    <h2>Just the tip</h2>
    <hr class="my-3">
    {% if submitted %}
    <h3>Thank you for your input.</h3>
    {% else %}
    <h3>Fill out the form</h3>
    <form action="{% url 'tabs:wishlist' %}" method="POST">
        {% csrf_token %}
        {{ wish_form.as_p }}
        <input class="btn btn-primary" type="submit" value="submit">
    </form>
    {% endif %}
</div>
{% endblock %}