POC/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts.views import (index, user_logout, account_view, health_check,
                            transactions, append_bet, validate_username)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^_ah/health', health_check, name='health_check'),
    url(r'^_ah/vm_health', health_check, name='health_check1'),
    url(r'^$', append_bet, name='index'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^epl/$', append_bet, name='epl'),
    url(r'^account/$', account_view, name='account'),
    url(r'^transactions/$', transactions, name='transactions'),
    url(r'tabs/', include('tabs.urls')),
]

accounts/urls.py
from django.conf.urls import url
from accounts import views

# SET THE NAMESPACE!
app_name = 'accounts'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^register/$', views.signup, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^ajax/validate_username/$',
        views.validate_username, name='validate_username'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^forgot_password/$', views.forgot_password, name='forgot_password'),
    url(r'^reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.set_password, name='set_password'),
]

tabs/urls.py
from django.conf.urls import url
from tabs import views

# SET THE NAMESPACE!
app_name = 'tabs'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^just-the-tip/$', views.just_the_tip, name='just-the-tip'),
    url(r'^wishlist/$', views.wishlist, name='wishlist'),
    url(r'^how-it-works/$', views.how_it_works, name='how-it-works'),
    url(r'^prizes/$', views.prizes, name='prizes'),
    url(r'^pools/$', views.pools_view, name='pools'),
    url(r'^pools/pool/(?P<pool_id>\d+$)', views.pool_view, name='pool')
]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

from accounts.models import Profile, PLGame


class UserRegistrationForm(UserCreationForm):
    # password1 = forms.CharField(widget=forms.PasswordInput())
    # confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean(self):
        cleaned_data = super(UserRegistrationForm, self).clean()
        password = cleaned_data.get("password1")
        confirm_password = cleaned_data.get("password2")

        if password != confirm_password:
            raise forms.ValidationError(
                "Error: Passwords do not match!"
            )

        try:
            User.objects.get(email=cleaned_data.get('email'))
            raise forms.ValidationError(
                {"email":
                     "Email address is already in use. Please reset your account"}
            )
        except ObjectDoesNotExist:
            pass

        # Validate that the username is not taken
        try:
            User.objects.get(username=cleaned_data.get("username"))
            raise forms.ValidationError(
                "Username is already taken. Please choose another"
            )
        except ObjectDoesNotExist:
            pass


class UserLoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password')


class ProfileForm(forms.ModelForm):
    """
    Used to get all other fields not in UserForm
    """

    class Meta:
        model = Profile
        fields = ['supported_team', 'bank_name', 'bank_account_number',
                  'branch_code', 'bank_balance']


class BetForm(forms.ModelForm):
    """ Where bets can be placed. """
    class Meta:
        model = PLGame
        fields = '__all__'

accounts/views.py
from datetime import datetime
import json
import logging
import pytz

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse, \
    HttpResponseForbidden, HttpResponseNotAllowed
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from accounts.models import User, Profile, PLGame, Transaction, BetForm, GamePool
from django.http import HttpResponse
from django.shortcuts import render, redirect
from accounts.forms import UserRegistrationForm, UserLoginForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from accounts.tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.contrib.auth.forms import SetPasswordForm

from tabs.views import create_pool_list

logging.basicConfig(level='INFO')
logger = logging.getLogger()


def forgot_password(request):
    user_valid, email_sent, email_address = True, False, None
    if request.method == 'POST':
        current_site = get_current_site(request)
        email_address = request.POST.get("email")
        try:
            user = User.objects.get(email=email_address, is_active=True)
        except ObjectDoesNotExist:
            user_valid = False
        else:
            mail_subject = 'Reset your Puntdoctor password.'
            message = render_to_string('accounts/forgot_password_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = email_address
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            logger.info(f"Sending email: {message} to {to_email}")
            email.send()
            email_sent = True
    return render(request, 'accounts/password_reset_email.html',
                  {'email_sent': email_sent, 'user_valid': user_valid,
                   'email_address': email_address})


def set_password(request, uidb64, token):
    """Update password based on email."""
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if not user:
        return HttpResponseForbidden()  # Just straight up forbid this request, looking fishy already!
    if request.method == 'POST':
        form = SetPasswordForm(user, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
            # TODO: toastr message that password has been changed.
    elif request.method == 'GET':
        form = SetPasswordForm(user)
    else:
        return HttpResponseNotAllowed(permitted_methods=['GET', 'POST'])
    form.fields['new_password2'].label = 'Confirm New Password'
    form.fields['new_password2'].longest = True
    return render(request, 'accounts/password_reset.html',
                  {'form': form, 'type': 'reset', 'uid': uid, 'token': token})


def signup(request):
    user_login_form = UserLoginForm(prefix='login')
    email_sent = False
    password_incorrect = False
    if request.method == 'POST':

        if request.POST.get("login"):
            username = request.POST.get('login-username')
            password = request.POST.get('login-password')

            user = authenticate(username=username, password=password)

            # If we have a user
            if user:
                # Check it the account is active
                if user.is_active:
                    # Log the user in.
                    login(request, user)
                    # Send the user back to some page.
                    # In this case their homepage.
                    return HttpResponseRedirect(reverse('index'))
            else:
                password_incorrect = True
                user_registration_form = UserRegistrationForm()

        elif request.POST.get("register"):  # Register
            user_registration_form = UserRegistrationForm(request.POST)
            if user_registration_form.is_valid():
                user = user_registration_form.save(commit=False)
                user.is_active = False
                user.save()
                current_site = get_current_site(request)
                mail_subject = 'Activate your Puntdoctor account.'
                message = render_to_string('accounts/acc_active_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                to_email = user_registration_form.cleaned_data.get('email')
                email = EmailMessage(
                            mail_subject, message, to=[to_email]
                )
                logger.info(f"Sending email: {message} to {to_email}")
                email.send()
                email_sent = True

                return render(request, 'accounts/registration.html',
                              {'user_registration_form': user_registration_form,
                               'user_login_form': user_login_form,
                               'email_sent': email_sent})
    else:
        user_registration_form = UserRegistrationForm()

    return render(request, 'accounts/registration.html',
                  {'user_registration_form': user_registration_form,
                   'user_login_form': user_login_form,
                   'password_incorrect': password_incorrect})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        profile = Profile.objects.create(user=user)
        profile.pools.add(GamePool.objects.get(pk=46))  # Join Global Rankings
        profile.save()
        # TODO: Login with login(request, user, backend)
        return redirect('index')
    else:
        return HttpResponse('Activation link is invalid!')


def health_check(request):
    """Returns 200 for a health check."""
    return HttpResponse("<h4>Healthy</h4>")


def index(request):
    return render(request, 'accounts/index.html')


def validate_username(request):
    """Ajax call to check whether a given username is taken."""
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(data)


@login_required
def account_view(request):
    if request.user.is_authenticated():
        try:
            user = request.user
            profile = Profile.objects.get(user=request.user.id)
        except NameError:
            profile = 'n/a'
    return render(request, 'accounts/account.html', {'profile': profile,
                                                     'user': user})


@login_required
def pool_rankings(request):
    """
    Method to return pool rankings to the left-sidebar.html page.
    This method should be called in any view that requires the pool rankings.
    :param request:
    :return: None
    """
    try:
        # Global Pool
        user = Profile.objects.get(user=request.user.id)
        total_members = Profile.objects.all().count()
        global_total = f"{user.global_ranking}/{total_members}"
        # Supporters Pool
        # Get the number of users in the Supporters Pool
        total_supporters = Profile.objects.filter(supporter_pool=
                                                  user.supporter_pool).count()
        supporter_total = f"{user.supporter_pool_ranking}/{total_supporters}"
        # For all other pools, get the rankings are in a list
        pool_rankings = json.loads(user.pool_rankings)
        pool_rankings_last_week = json.loads(user.pool_rankings_last_week)
        pool_rankings_updated = []
        for pr, prlw in zip(pool_rankings, pool_rankings_last_week):
            combined = {'pool_movement': prlw['pool_standing'] - pr['pool_standing']}
            pool_rankings_updated.append({**pr, **combined})
    except Exception as e:
        logger.error("Can't rank pools in sidebar.")
        logger.error(e.with_traceback(e.__traceback__))
        global_total = supporter_total = pool_rankings_updated = None
        user.global_ranking_last_week = user.global_ranking = 0
        user.supporter_pool_ranking_last_week = user.supporter_pool_ranking = 0

    return {'global_total': global_total,
            'global_movement': user.global_ranking_last_week -
                               user.global_ranking,
            'supporter_total': supporter_total,
            'supporter_movement': user.supporter_pool_ranking_last_week -
                                  user.supporter_pool_ranking,
            'supporter_pool': user.supporter_pool,
            'pool_rankings': pool_rankings_updated}


def append_bet(request, season='2018/2019'):
    """
    This is the epl view. Need to rename this view.
    :param request:
    :return:
    """
    # TODO: accept season argument and add season to page
    pool_rankings = {}  # give default value
    # Get pools rankings from pool_rankings()
    try:
        user = Profile.objects.get(user=request.user.id)
        pool_rankings = create_pool_list(request)

templates/accounts/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration to Puntdoctor,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/account.html
{% extends 'accounts/base.html' %}

{% block left_sidebar %}
{% include "tabs/left-sidebar.html" %}
{% endblock %}

{% block body_block %}
<div class="main-content">
    <h2>Account</h2>
    <hr class="my-3">
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label>Username</label>
                <h5>{{ user.username }}</h5>
            </div>

            <div class="form-group">
                <label>Email Address Password</label>
                <h5>{{ user.email }}</h5>
            </div>

            <div class="form-group">
                <label>Account Balance</label>
                <h5>{{ profile.game_account_balance }}</h5>
            </div>

            <div class="form-group">
                <label>Account Accrued Balance</label>
                <h5>{{ profile.game_account_accrued_balance }}</h5>
            </div>

            <div class="form-group">
                <label>Bank Name</label>
                <h5>{{ profile.bank_name }}</h5>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="google-site-verification" content="A_RirXxI65BB0uvne6IDRYZWUrnGEsMyH1H9HhrDb7A" />
    <title>{% block title %}PuntDoctor{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    {% load staticfiles %}
    <link href="{% static 'base.css' %}" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Exo:400,800,900" rel="stylesheet">
    <link rel="shortcut icon" href="{% static "favicon.png" %}" />
    <script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </head>

  <body>

  <div id="registerModal" class="register-modal">
    <!-- Modal content -->
    <div class="register-modal-content">
      <section>
        <div class="row">
          <div class="col-12">
            <h4 style="color:white" class="text-left">Register</h4>
            <hr>
            {% if registered %}
            <h1>Thank you for registering!</h1>
            {% else %}
            <form enctype="multipart/form-data" method="POST">
              {% csrf_token %}
              {{ user_form.as_p }}
              <input class="btn btn-link" type="submit" name="" value="Register">
            </form>
            {% endif %}
          </div>
        </div>
      </section>
      <p class="modal-close">Later</p>
    </div>
  </div>


  <!--Main Navigation-->
    <div class="header-container">
      <div class="navbar-image">
        <img src="{% static "puntdoctor_logo_cropped.png" %}" alt="PuntDoctor Logo" width="120">
      </div>
      <div class="nav-and-title-container"></div>
      <nav class="navbar navbar-toggleable-md">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a href="{% url 'epl' %}">
          <!--Punt Doctor-->
          <div class="navbar-title">
            <h3>Punt Doctor</h3>
          </div>
        </a>
        <div class="collapse navbar-collapse" id="navbarNav">
        {# Django Home Link / Admin Link / Register Link#}
          <ul class="navbar-nav">
            {# Some logic on what to display for last item#}

            <li><a style="margin-top:0.5em;" class="nav-link" href="{% url 'epl' %}">English Premier League</a></li>
            <li><a class="nav-link" href="#">Rugby<span class="nav-link-sub"><br>coming soon!</span></a></li>
            <li><a class="nav-link" href="#">Cricket<span class="nav-link-sub"><br>coming soon!</span></a></li>
            {% if user.is_authenticated %}
            <li class="account-balance">
              <div><a class="nav-link" id="balance" href="">R{{ user.profile.game_account_balance }}<span class="nav-link-sub"><br>Available Balance</span></a></div>
              <div><a class="nav-link" id="balance" href="">R{{ user.profile.game_account_accrued_balance }}<span class="nav-link-sub"><br>Accumulated Balance</span></a></div>
            </li>
            {% endif %}
          </ul>
        </div>
        {% if user.is_authenticated %}
        <div class="dropdown">
          <button class="btn btn-md btn-custom dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-user-circle" aria-hidden="true"></i>  {{ user.username }}
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'account' %}">Account</a>
            <a class="dropdown-item" href="{% url 'transactions' %}">Transactions</a>
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
          </div>
        </div>
        {% else %}
        <div class="navbar-login">
            <form class="form-inline" method="post" action="{% url 'accounts:user_login' %}">
              {% csrf_token %}
              <input type="text" class="form-control form-control-sm mr-1" id="inlineFormInput" placeholder="Username" name="username">
              <input type="password" class="form-control form-control-sm mr-3" id="inlineFormInputGroup" placeholder="Password" name="password">
              <button type="submit" class="btn btn-primary btn-sm mr-3">Login</button>
              <!--<div class="fb-login-button" data-max-rows="1" data-size="medium" data-button-type="login_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false"></div>-->
              <button id="registerButton" class="btn btn-primary btn-sm">Register</button></li>
            </form>
        </div>
        {% endif %}
      </nav>
      <h6 class="tagline">The ultimate free sports prediction game</h6>
    </div>

    <div class="container-fluid main-page-container">
    <!--Left Sidebar-->
    {% block left_sidebar %}
    {% endblock %}
    <div class="page-content">
      <!--Main Content Area-->
      {% block body_block %}
      {% endblock %}
    </div>
    <!--Right Sidebar-->
    {% block right_sidebar %}
    {% endblock %}
    </div>

    <footer>
      <div class="main-footer">
        <div class="container">
          <div class="row">
            <div class="col-md-5">
              <a href="{% url 'epl' %}"><h5 class="footer-logo">PuntDoctor</h5></a>
              <div class="row">
                <div class="col-6">
                  <ul class="list-unstyled">
                    <li><a href="{% url 'tabs:just-the-tip' %}">Just the Tip</a></li>
                    <li><a href="{% url 'tabs:pools' %}">Pools</a></li>
                    <li><a href="{% url 'transactions' %}">Transactions</a></li>
                  </ul>
                </div>
                <div class="col-6">
                  <ul class="list-unstyled">
                    <li><a href="{% url 'tabs:how-it-works' %}">How it works</a></li>
                    <li><a href="{% url 'tabs:prizes' %}">Prizes</a></li>
                    <li><a href="{% url 'account' %}">Account</a></li>
                  </ul>
                </div>
              </div>
              <div class="footer-copyright row" style="">© 2017 PuntDoctor. All rights reserved.</div>
              <!--<ul class="nav">-->
                <!--<li class="nav-item"><a href="" class="nav-link pl-0"><i class="fa fa-facebook fa-lg"></i></a></li>-->
                <!--<li class="nav-item"><a href="" class="nav-link"><i class="fa fa-twitter fa-lg"></i></a></li>-->
                <!--<li class="nav-item"><a href="" class="nav-link"><i class="fa fa-github fa-lg"></i></a></li>-->
                <!--<li class="nav-item"><a href="" class="nav-link"><i class="fa fa-instagram fa-lg"></i></a></li>-->
              <!--</ul>-->
              <br>
            </div>

          </div>
        </div>
      </div>
    </footer>

    {% block javascript %}

    {% endblock %}
  </body>
  <div id="fb-root"></div>
<script>
    //plugin bootstrap minus and plus
    //http://jsfiddle.net/laelitenetwork/puJ6G/
    $('.btn-number').click(function(e){
        e.preventDefault();

        fieldName = $(this).attr('data-field');
        type      = $(this).attr('data-type');
        var input = $("input[name='"+fieldName+"']");
        var currentVal = parseInt(input.val());
        if (!isNaN(currentVal)) {
            if(type == 'minus') {

                if(currentVal > input.attr('min')) {
                    input.val(currentVal - 50).change();
                }
                if(parseInt(input.val()) == input.attr('min')) {
                    $(this).attr('disabled', true);
                }
            } else if(type == 'plus') {

                if(currentVal < input.attr('max')) {
                    input.val(currentVal + 50).change();
                }
                if(parseInt(input.val()) == input.attr('max')) {
                    $(this).attr('disabled', true);
                }

            }
        } else {
            input.val(0);
        }
    });
    $('.input-number').focusin(function(){
        $(this).data('oldValue', $(this).val());
    });
    $('.input-number').change(function() {

        minValue =  parseInt($(this).attr('min'));
        maxValue =  parseInt($(this).attr('max'));
        valueCurrent = parseInt($(this).val());

        name = $(this).attr('name');
        if(valueCurrent >= minValue) {
            $(".btn-number[data-type='minus'][data-field='"+name+"']").removeAttr('disabled')
        } else {
            alert('Sorry, the minimum value was reached');
            $(this).val($(this).data('oldValue'));
        }
        if(valueCurrent <= maxValue) {
            $(".btn-number[data-type='plus'][data-field='"+name+"']").removeAttr('disabled')
        } else {
            alert('Sorry, the maximum value was reached');
            $(this).val($(this).data('oldValue'));
        }

    });
    $(".input-number").keydown(function (e) {
        // Allow: backspace, delete, tab, escape, enter and .
        if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 190]) !== -1 ||
            // Allow: Ctrl+A
            (e.keyCode == 65 && e.ctrlKey === true) ||
            // Allow: home, end, left, right
            (e.keyCode >= 35 && e.keyCode <= 39)) {
            // let it happen, don't do anything
            return;
        }
        // Ensure that it is a number and stop the keypress
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
            e.preventDefault();
        }
    });


//    Login with Facebook
      (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9&appId=180235935384582";
          fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));

</script>

</html>

templates/accounts/forgot_password_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to reset your password
http://{{ domain }}{% url 'accounts:set_password' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/index.html
{% extends "accounts/base.html" %}
{% block body_block %}

<div class="full-background">
    {% if user.is_authenticated %}
        <!--<h2>Welcome {{ user.username }}!</h2>-->
    {% else %}
        <div class="container">
            {% load staticfiles %}
            <div class="jumbotron landing-login">
                <div class="container">
                    <div class="row">
                        <div class="col-8">
                            <h1 class="display-3">Welcome to PuntDoctor</h1>
                            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
                        </div>
                        <div class="col-4 text-right">
                            <img src="{% static "doctor.png" %}" alt="PuntDoctor Logo" width="200">
                        </div>
                    </div>
                    <hr class="my-4">
                    <div class="row">
                        <div class="col">
                            <form class="form-inline" method="post" action="{% url 'accounts:user_login' %}">
                                {% csrf_token %}
                                <label class="sr-only" for="inlineFormInput">Name</label>
                                <input type="text" name="username" class="form-control mb-2 mr-sm-2 mb-sm-0" id="inlineFormInput" placeholder="Username">
                                <label class="sr-only" for="inlineFormInputGroup">Username</label>
                                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                    <input type="text" name="password" class="form-control" id="inlineFormInputGroup" placeholder="Password">
                                </div>
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a class="register-button" href="{% url 'accounts:register' %}">Register</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
</div>

<div style="background: #9fc2d4; margin: 0 -1em 0 -2em">
    <div  class="container">
        <div class="row landing-info">
            <div class="col p-5">
                <h1>Call to action one</h1>
                <h5 class="mb-3">These are some reasons</h5>
                <ul>
                    <li><h6>This is a reason</h6></li>
                    <li><h6>Another reason</h6></li>
                    <li><h6>One more reason</h6></li>
                </ul>
            </div>
            <div class="col">
            </div>
        </div>
    </div>
</div>

<div style="background: #69a2bf; margin: 0 -1em 0 -2em">
    <div  class="container">
        <div class="row landing-info">
            <div class="col p-5">
            </div>
            <div class="col p-5">
                <h1>Call to action two</h1>
                <h5 class="mb-3">These are some reasons</h5>
                <ul>
                    <li><h6>This is a reason</h6></li>
                    <li><h6>Another reason</h6></li>
                    <li><h6>One more reason</h6></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div style="background: #9fc2d4; margin: 0 -1em 0 -2em">
    <div  class="container">
        <div class="row landing-info">
            <div class="col p-5">
                <h1>Call to action three</h1>
                <h5 class="mb-3">These are some reasons</h5>
                <ul>
                    <li><h6>This is a reason</h6></li>
                    <li><h6>Another reason</h6></li>
                    <li><h6>One more reason</h6></li>
                </ul>
            </div>
            <div class="col">
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block body_block %}
  <div class="container">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'accounts:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">
          <input type="submit" name="" value="Login">
        </form>
  </div>
{% endblock %}